package com.video.trimmer.utils;

import android.content.Context;
import android.os.Environment;

import com.video.trimmer.R;

public class Constants {
    public  Context context;
    public  String CONVERTED_AUDIO_FOLDER_PATH;
    public  String TRIMMED_AUDIO_FOLDER_PATH;
    public  String TRIMMED_VIDEO_FOLDER_PATH;
    public  String REMOVED_AUDIO_VIDEO_FOLDER_PATH;
    public  String ADD_AUDIO_TO_VIDEO_FOLDER_PATH;
    public  String CREATED_VIDEO_WITH_IMAGES_FOLDER_PATH;
    public  String TEMP_FOLDER_PATH;
    public Constants(Context context) {
        this.context=context;
        CONVERTED_AUDIO_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Converted Audios/";
        TRIMMED_AUDIO_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Trimmed Audios/";
        TRIMMED_VIDEO_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Trimmed Videos/";
        REMOVED_AUDIO_VIDEO_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Audio Removed Vidoes/";
        ADD_AUDIO_TO_VIDEO_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Audio Added Videos/";
        CREATED_VIDEO_WITH_IMAGES_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Created Videos/";
        TEMP_FOLDER_PATH= context.getFilesDir().getAbsolutePath()+"/Video to MP3 converter Outputs/Tmp/";
    }
    public static int PERMISSION_CODE=1001;
    public static int PERMISSIONS_REQUSTCODE2 = 937;
    public static int PERMISSION_CODE2=1002;
    public static int AUDIO_CUTTER_ICON= R.drawable.ic_audio_trimmer;
    public static int VIDEO_CUTTER_ICON= R.drawable.ic_video_trimmer;
    public static int VIDEO_TO_AUDIO_ICON= R.drawable.ic_video_to_audio;
    public static int REMOVE_AUDIO_ICON= R.drawable.ic_remove_audio;
    public static int ADD_AUDIO_ICON= R.drawable.ic_add_music;
    public static int CREATE_VIDEO_ICON= R.drawable.ic_image_to_video;
    public  static  String LAUNCH_OR_NOT_KEY="launchornotkey";
    public static String URI_INTENT_KEY= "uri";
    public static String NAME_INTENT_KEY= "name";
    public static String TYPE_INTENT_KEY= "type";
    public static String DURATION_INTENT_KEY= "drationIntentKey";
    public static String AUDIO_URI_INTENT_KEY= "audiouri";
    public static String MAIN_TYPE_INTENT_KEY= "maintype";
    public static final int DEFAULT_BUFFER_SIZE = 1 * 1024 * 1024;
    public static final String TAG = "AudioExtractorDecoder";
    public static final String EXTRA_VIDEO_PATH = "EXTRA_VIDEO_PATH";
    public static final String VIDEO_TOTAL_DURATION = "VIDEO_TOTAL_DURATION";
    public static final String INTENT_DESTINATION_VIDEO_PATH = "trimmeddestiationvideopath";
    public  static String SILLI_TEMP_FOLDER_PATH= Environment.getExternalStorageDirectory().getAbsolutePath()+"/Pictures/SiliCompressor/";
    public static String FOLDER_NAME_INTENT_KEY="foldernameintentkey";
    public static String AUDIOSIZE_INTENT_KEY="audioSizeIntentkey";
    public static String FROM_ADD_AUDIO_KEY="fromaddaudiokeytosendbool";
    public static final String ENGLISH = "en";
    public static final String HINDI = "hi";
    public static final String SPANISH = "es";
    public static final String ARABIC = "ar";
    public static final String BENGALI = "bn";
    public static final String FRENCH = "fr";
    public static final String GERMAN = "de";
    public static final String INDONESIAN = "in";
    public static final String ITALIAN = "it";
    public static final String JAPANESE = "ja";
    public static final String CHINESE = "zh";
    public static final String PORTUGUESE = "pt";
    public static final String RUSSIAN = "ru";
    public static final String SERBIAN = "sr";
    public static final String THAI = "th";
    public static final String TURKISH = "tr";
    public static final String URDU = "ur";
    public static final String AFRICAN = "af";
    public static final String ARMANIA = "hy-AM";
    public static final String AZERBAIJAAN = "az";
    public static final String BULGARIAN = "bg";
    public static final String BALRUSIAN = "be";
    public static final String CROATIA = "hr";
    public static final String DANNISH = "da";
    public static final String DUTCH = "nl";
    public static final String PHILIPINE = "fil";
    public static final String FINNISH = "fi";
    public static final String HIBRU = "iw";
    public static final String ICELANDIC = "is";
    public static final String KAZAKISTAN = "kk";
    public static final String KOREAN = "ko";
    public static final String MALAYSIA = "ms";
    public static final String NORWAY = "nb";
    public static final String POLISH = "pl";
    public static final String ROMANIA = "ro";
    public static final String SLOVAK = "sk";
    public static final String SWEDISH = "sv";
    public static final String UZBIK = "uz";
    public static final String VIETNAM = "vi";
}
